In [32]:
text = "Located on the southern tip of Lake Union, the Hilton Garden Inn Seattle Downtown hotel is perfectly located for business and leisure. \nThe neighborhood is home to numerous major international companies including Amazon, Google and the Bill & Melinda Gates Foundation. A wealth of eclectic restaurants and bars make this area of Seattle one of the most sought out by locals and visitors. Our proximity to Lake Union allows visitors to take in some of the Pacific Northwest's majestic scenery and enjoy outdoor activities like kayaking and sailing. over 2,000 sq. ft. of versatile space and a complimentary business center. State-of-the-art A/V technology and our helpful staff will guarantee your conference, cocktail reception or wedding is a success. Refresh in the sparkling saltwater pool, or energize with the latest equipment in the 24-hour fitness center. Tastefully decorated and flooded with natural light, our guest rooms and suites offer everything you need to relax and stay productive. Unwind in the bar, and enjoy American cuisine for breakfast, lunch and dinner in our restaurant. The 24-hour Pavilion Pantry? stocks a variety of snacks, drinks and sundries."

text

"Located on the southern tip of Lake Union, the Hilton Garden Inn Seattle Downtown hotel is perfectly located for business and leisure. \nThe neighborhood is home to numerous major international companies including Amazon, Google and the Bill & Melinda Gates Foundation. A wealth of eclectic restaurants and bars make this area of Seattle one of the most sought out by locals and visitors. Our proximity to Lake Union allows visitors to take in some of the Pacific Northwest's majestic scenery and enjoy outdoor activities like kayaking and sailing. over 2,000 sq. ft. of versatile space and a complimentary business center. State-of-the-art A/V technology and our helpful staff will guarantee your conference, cocktail reception or wedding is a success. Refresh in the sparkling saltwater pool, or energize with the latest equipment in the 24-hour fitness center. Tastefully decorated and flooded with natural light, our guest rooms and suites offer everything you need to relax and stay productive. Unwind in the bar, and enjoy American cuisine for breakfast, lunch and dinner in our restaurant. The 24-hour Pavilion Pantry? stocks a variety of snacks, drinks and sundries."

In [33]:
# Step 1: Split the corpus data

corpus = list(text.split())
print(len(corpus))

print(corpus[:10])

184
['Located', 'on', 'the', 'southern', 'tip', 'of', 'Lake', 'Union,', 'the', 'Hilton']

In [34]:
# Step 2: Get the unique data

unique_edata = set(corpus)
print(len(unique_edata))

print(corpus[:10])

134
['Located', 'on', 'the', 'southern', 'tip', 'of', 'Lake', 'Union,', 'the', 'Hilton']

In [35]:
# Step 3: Generate Unique Identity for each word in the corpus

text_to_int = {}

for i,j in enumerate(unique_edata):
    text_to_int.update({j:i})

In [36]:
text_to_int

{'is': 0,
 'Foundation.': 1,
 'leisure.': 2,
 'A': 3,
 'wealth': 4,
 'tip': 5,
 'conference,': 6,
 'energize': 7,
 'center.': 8,
 'cuisine': 9,
 'need': 10,
 'pool,': 11,
 'light,': 12,
 'rooms': 13,
 'success.': 14,
 'Bill': 15,
 'you': 16,
 'locals': 17,
 'in': 18,
 'companies': 19,
 'enjoy': 20,
 'drinks': 21,
 'Our': 22,
 'lunch': 23,
 'fitness': 24,
 'sought': 25,
 'our': 26,
 'Pacific': 27,
 'Melinda': 28,
 'hotel': 29,
 'sq.': 30,
 'and': 31,
 'ft.': 32,
 'to': 33,
 'Tastefully': 34,
 'relax': 35,
 'numerous': 36,
 'by': 37,
 'technology': 38,
 'or': 39,
 'Pantry?': 40,
 'A/V': 41,
 'area': 42,
 'reception': 43,
 "Northwest's": 44,
 'The': 45,
 'stocks': 46,
 'your': 47,
 'Seattle': 48,
 'Unwind': 49,
 'eclectic': 50,
 'restaurant.': 51,
 'natural': 52,
 'of': 53,
 '2,000': 54,
 'Garden': 55,
 'State-of-the-art': 56,
 'productive.': 57,
 'restaurants': 58,
 'Inn': 59,
 'allows': 60,
 'equipment': 61,
 'latest': 62,
 'the': 63,
 'kayaking': 64,
 'cocktail': 65,
 'complimentary': 66,
 'sundries.': 67,
 'breakfast,': 68,
 'guarantee': 69,
 '24-hour': 70,
 'including': 71,
 'dinner': 72,
 'with': 73,
 'variety': 74,
 'over': 75,
 'Gates': 76,
 'take': 77,
 'international': 78,
 'outdoor': 79,
 'Hilton': 80,
 'this': 81,
 'one': 82,
 'neighborhood': 83,
 'versatile': 84,
 'guest': 85,
 'suites': 86,
 'activities': 87,
 'space': 88,
 'helpful': 89,
 'will': 90,
 'sparkling': 91,
 'Pavilion': 92,
 'snacks,': 93,
 'perfectly': 94,
 'proximity': 95,
 'sailing.': 96,
 'some': 97,
 'Refresh': 98,
 'wedding': 99,
 'home': 100,
 'Union': 101,
 'Amazon,': 102,
 'most': 103,
 'business': 104,
 'Union,': 105,
 'scenery': 106,
 'make': 107,
 'majestic': 108,
 '&': 109,
 'offer': 110,
 'saltwater': 111,
 'stay': 112,
 'Lake': 113,
 'staff': 114,
 'flooded': 115,
 'American': 116,
 'visitors.': 117,
 'Located': 118,
 'decorated': 119,
 'out': 120,
 'everything': 121,
 'Downtown': 122,
 'bar,': 123,
 'on': 124,
 'for': 125,
 'major': 126,
 'like': 127,
 'a': 128,
 'Google': 129,
 'visitors': 130,
 'located': 131,
 'southern': 132,
 'bars': 133}

In [37]:
# Convert 'Text' data into unique int value identity

corpus_int = []

for i in range(0,len(corpus)):
    # print(corpus[i])
    corpus_int.append(text_to_int[corpus[i]])

In [38]:
corpus_int

[118,
 124,
 63,
 132,
 5,
 53,
 113,
 105,
 63,
 80,
 55,
 59,
 48,
 122,
 29,
 0,
 94,
 131,
 125,
 104,
 31,
 2,
 45,
 83,
 0,
 100,
 33,
 36,
 126,
 78,
 19,
 71,
 102,
 129,
 31,
 63,
 15,
 109,
 28,
 76,
 1,
 3,
 4,
 53,
 50,
 58,
 31,
 133,
 107,
 81,
 42,
 53,
 48,
 82,
 53,
 63,
 103,
 25,
 120,
 37,
 17,
 31,
 117,
 22,
 95,
 33,
 113,
 101,
 60,
 130,
 33,
 77,
 18,
 97,
 53,
 63,
 27,
 44,
 108,
 106,
 31,
 20,
 79,
 87,
 127,
 64,
 31,
 96,
 75,
 54,
 30,
 32,
 53,
 84,
 88,
 31,
 128,
 66,
 104,
 8,
 56,
 41,
 38,
 31,
 26,
 89,
 114,
 90,
 69,
 47,
 6,
 65,
 43,
 39,
 99,
 0,
 128,
 14,
 98,
 18,
 63,
 91,
 111,
 11,
 39,
 7,
 73,
 63,
 62,
 61,
 18,
 63,
 70,
 24,
 8,
 34,
 119,
 31,
 115,
 73,
 52,
 12,
 26,
 85,
 13,
 31,
 86,
 110,
 121,
 16,
 10,
 33,
 35,
 31,
 112,
 57,
 49,
 18,
 63,
 123,
 31,
 20,
 116,
 9,
 125,
 68,
 23,
 31,
 72,
 18,
 26,
 51,
 45,
 70,
 92,
 40,
 46,
 128,
 74,
 53,
 93,
 21,
 31,
 67]

In [42]:
# Generate input Sequence 
input_Sequence = []
for i in range(0,len(corpus_int)):
    input_Sequence.append(corpus_int[: i +1])

In [44]:
# Generate Padded Sequence
from keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(input_Sequence)

padded

Using TensorFlow backend.

array([[  0,   0,   0, ...,   0,   0, 118],
       [  0,   0,   0, ...,   0, 118, 124],
       [  0,   0,   0, ..., 118, 124,  63],
       ...,
       [  0,   0, 118, ...,  53,  93,  21],
       [  0, 118, 124, ...,  93,  21,  31],
       [118, 124,  63, ...,  21,  31,  67]])